### PR TITLE
Approach without `dep`

### PR DESCRIPTION
**Pull request by tzdybal**
After re-working everything, it seems that there is no need to keep full `dep` vendoring in this project.
New solution propose using plain `git` to get all the necessary dependencies for `ethash`.

The main problem with `dep` (and `go get`) is that there is a cyclic dependency between `ethash` and `go-ethereum`.

After merging changes to `go-ethereum`, we should remove the `git checkout ...` line and use `master` branch.

### CODE REVIEW

**Comment by mikeyb** [comment]
> The main problem with dep (and go get) is that there is a cyclic dependency between ethash and go-ethereum.

> Can we do it without another necessary revision to change geth branch to master?
> Can we use just ‘pushd [..]geth’ instead of the ‘pushd . && [..]’ syntax? (AFK)
> Either way, nitpicks.

I will leave this for others to discuss the technicals, but it sounds like the most beneficial outcome is that remove the cyclic dependency?  I am all for this end result to boost end user experience.

**Comment by tzdybal** [comment]
@whilei I don't see option to do it without change. Actually, as long as branch exists, it's gonna work.
And regarding `pushd` - it can be done as you pointer. But I'll leave as is, because it's to be deleted anyways after switching back to master branch.

**Comment by tzdybal** [comment]
@whilei  @phyro @mikeyb Fixed all CI issues. Please re-review, and merge the branch (as I may not be able to do it next few days).

**Comment by whilei** [comment]
💚 LGTM

**Pull request merged**
