### PR TITLE
appveyor: use go test instead of nonexisting Debug dir test

### PR DESCRIPTION
**Pull request by whilei**

### CODE REVIEW

**Comment by whilei** [comment]
cc @tzdybal

**Comment by tzdybal** [comment]
IIRC `Debug` directory is created by Visual Studio during build. It's completely different set of tests - this tests C implementation, not go bindings.

**Comment by tzdybal** [comment]
Btw - I'm also working on making this runnable (updated Visual Studio and boost libraries, etc)

**Comment by whilei** [comment]
Great. I should have mentioned (though probably just for documentation's sake) that this was a response the Appveyor test failure here https://ci.appveyor.com/project/realcodywburns/ethash/builds/21083649 (from #4)

**Comment by tzdybal** [comment]
I'm closing this as #4 is merged already.

**Pull request closed without merging**
